@BASE_URL = http://nathang2018:5000/api/v1

###
POST {{BASE_URL}}/account/create/Nate314

###
POST {{BASE_URL}}/account/create/Bobbyjuba

###
POST {{BASE_URL}}/account/create/Amadeusine

###
POST {{BASE_URL}}/account/create/Angad

###
GET {{BASE_URL}}/account/799968e2-822e-447f-8edc-c84f86ce47eb

###
GET {{BASE_URL}}/account/c59a5748-cd3b-4bd9-94ff-40ca2bf841a9

###
POST {{BASE_URL}}/account/destroy/6c1c339c-dfa0-4f6a-9dab-14e0062ea9f0

###
GET {{BASE_URL}}/match/799968e2-822e-447f-8edc-c84f86ce47eb

###
GET {{BASE_URL}}/match/c59a5748-cd3b-4bd9-94ff-40ca2bf841a9

###
GET {{BASE_URL}}/match/cbdd0338-4bbd-4c58-90ec-774395bde1b9

###
GET {{BASE_URL}}/match/e898d20e-a9d6-4dda-89ce-c3941f83513e

###
POST {{BASE_URL}}/messages/send/4a873540-d13a-4f7e-b3b6-0eeb7db2275e
Content-Type: application/json

{
    "userID": "c59a5748-cd3b-4bd9-94ff-40ca2bf841a9",
    "message": "Hello there"
}

###
GET {{BASE_URL}}/messages/all/4a873540-d13a-4f7e-b3b6-0eeb7db2275e
Content-Type: application/json
